services:
   orders-service:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./src:/app/src
      container_name:
        orders
      command: yarn dev
      ports:
        ["8001:8001"]
  