services:
   payment-service:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./src:/app/src
      container_name:
        payment
      command: yarn dev
      ports:
        ["8002:8002"]
  