services:
   auth-service:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./src:/app/src
      container_name:
        auth
      command: yarn dev
      ports:
        ["8000:8000"]
  